# Generated by Django 6.0 on 2025-12-12 02:34

import django.db.models.deletion
import media.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('cursor', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=media.utils.media_upload_path)),
                ('storage_backend', models.CharField(choices=[('LOCAL', 'Local'), ('AWS', 'Aws'), ('GCP', 'Gcp')], default='local', max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail_small', models.ImageField(blank=True, null=True, upload_to='thumbnails/small/')),
                ('thumbnail_medium', models.ImageField(blank=True, null=True, upload_to='thumbnails/medium/')),
                ('thumbnail_large', models.ImageField(blank=True, null=True, upload_to='thumbnails/large/')),
                ('thumbnails_generated', models.BooleanField(db_default=False, default=False)),
                ('is_reusable', models.BooleanField(db_default=False, default=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.useraccount')),
            ],
            options={
                'db_table': 'media',
                'ordering': ['-created_on'],
            },
        ),
    ]
