# Generated by Django 6.0 on 2025-12-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='storage_backend',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('AWS', 'Aws'), ('GCP', 'Gcp')], default='LOCAL', max_length=20),
        ),
    ]
