# Generated by Django 6.0 on 2025-12-12 02:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('cursor', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=100)),
                ('identifier_type', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE_NUMBER', 'Phone Number')], max_length=100)),
                ('password', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='INACTIVE', max_length=100)),
            ],
            options={
                'db_table': 'user_account',
                'ordering': ['cursor'],
            },
        ),
    ]
