# Generated by Django 6.0 on 2025-12-17 12:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('cursor', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=100)),
                ('password', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='INACTIVE', max_length=100)),
            ],
            options={
                'db_table': 'user_account',
                'ordering': ['cursor'],
            },
        ),
        migrations.CreateModel(
            name='RevokedToken',
            fields=[
                ('cursor', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('token', models.TextField(db_index=True, unique=True)),
                ('expires_on', models.DateTimeField()),
            ],
            options={
                'ordering': ['cursor'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('cursor', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('reset_password_token', models.TextField(db_index=True, unique=True)),
                ('expires_on', models.DateTimeField()),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='auth.useraccount')),
            ],
            options={
                'ordering': ['cursor'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('cursor', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('users', models.ManyToManyField(related_name='permissions', to='auth.useraccount')),
            ],
            options={
                'ordering': ['cursor'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('cursor', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default', models.BooleanField(default=False)),
                ('permissions', models.ManyToManyField(related_name='roles', to='auth.permission')),
                ('users', models.ManyToManyField(related_name='roles', to='auth.useraccount')),
            ],
            options={
                'ordering': ['cursor'],
                'abstract': False,
            },
        ),
    ]
