# Generated by Django 6.0 on 2025-12-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
