# Generated by Django 6.0 on 2025-12-15 19:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0002_alter_useraccount_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedToken',
            fields=[
                ('cursor', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('token', models.TextField(db_index=True, unique=True)),
                ('expires_on', models.DateTimeField()),
            ],
            options={
                'ordering': ['cursor'],
                'abstract': False,
            },
        ),
    ]
