# Generated by Django 6.0 on 2025-12-15 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0003_revokedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('cursor', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('reset_password_token', models.TextField(db_index=True, unique=True)),
                ('expiration_time', models.DateTimeField()),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='auth.useraccount')),
            ],
            options={
                'ordering': ['cursor'],
                'abstract': False,
            },
        ),
    ]
