# Generated by Django 6.0 on 2025-12-15 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresettoken',
            old_name='expiration_time',
            new_name='expires_on',
        ),
    ]
