# Generated by Django 6.0 on 2025-12-17 13:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('cursor', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('email_content', models.TextField()),
                ('short_content', models.TextField()),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['cursor'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('cursor', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user_info.userinfo')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notification.notificationtemplate')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['cursor'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDispatch',
            fields=[
                ('cursor', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('links', models.JSONField(blank=True, default=list, null=True)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WEBSOCKET', 'Websocket')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered'), ('READ', 'Read')], default='PENDING', max_length=50)),
                ('sent_on', models.DateTimeField(blank=True, null=True)),
                ('delivered_on', models.DateTimeField(blank=True, null=True)),
                ('read_on', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('extra_info', models.JSONField(blank=True, default=dict, null=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='notification.notification')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_dispatches', to='user_info.userinfo')),
            ],
            options={
                'db_table': 'notification_dispatches',
                'ordering': ['cursor'],
            },
        ),
    ]
