# Generated by Django 6.0 on 2025-12-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='staff',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notificationdispatch',
            old_name='staff',
            new_name='user',
        ),
    ]
