# Generated by Django 6.0 on 2025-12-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_staff_notification_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='user_info',
        ),
    ]
